import Head from 'next/head'
import { GetStaticProps } from 'next';

import Banner from '../components/BannerHome'
import { DisplayCourses } from '../components/DisplayCourses'

import { CoursesType } from '../types/courses.type';
import Header from '../components/Header';
import { createClient } from '../../prismicio';

interface HomeProps {
  courses: {
    data: CoursesType
    slugs: string[]
  }[]
}

export default function Home({ courses }: HomeProps) {
  console.log(courses)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Banner />
        <DisplayCourses
          courses={courses}
        />
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async ({ previewData }) => {
  const client = createClient({ previewData });

  const courses = await client.getAllByType('title', { graphQuery: `
    {
      title {
        title
        images {
          card
        }
      }
    }
  ` });

  return {
    props: {
      courses
    },
  } 
}
